
site_name: Documentação FastAPI
nav:
  
  - Home: index.md
  - Instalação: instalacao.md
  - Exemplos: exemplos.md
  - Execução: execucao.md
  - Melhores Práticas e Dicas: melhores_praticas.md
  - Referências: referencias.
docs_dir: docs-FastApi/docs
theme: readthedocs
